### PR TITLE
translate: pt-br

### PR DESCRIPTION
**Pull request by diegoeis**
I created a pt-br.html file with the translated content.

To CSS work online in gh-pages, I put on CSS link tag a {{ site.url }}. I don't know if this is a good idea.
You can see working on http://diegoeis.github.io/code-guide/pt-br/

What you think?

PS: I called the developers of the Brazilian community to work on this project too. Check it out: http://tableless.com.br/code-guide-mdo/

### CODE REVIEW

**Comment by mdo** [comment]
Looks awesome, but I don't want to maintain the translations here. I know no other language and keeping things up to date sounds like rather difficult to me :). I'm more than happy to link to them from the readme though <3.

**Comment by diegoeis** [comment]
:-(

I will maintain the pt-br version on my github, ok?
Can you link in Read Me?

Thx!

**Comment by mdo** [comment]
> I will maintain the pt-br version on my github, ok?
> Can you link in Read Me?

Sorry, I don't mean to be rude. I just don't think it's a good idea to keep them all together. I'd rather give you all the credit through your GitHub account.

And yes, of course! Open a PR so you at least get some credit for your work here <3.

**Comment by diegoeis** [comment]
Rude? Never! Maybe the problem is my unclear english! ;-)
Don't worry, man!

Great!
I will do that! ;-)

**Pull request closed without merging**
