### PR TITLE
CSS nomenclature

### PR DESCRIPTION
**Pull request by mdo**
This is an early PR to gather some feedback on what else folks would like to see in the Code Guide. I often run into problems when describing the content of a CSS file and until a couple years ago I didn't know most of these terms by heart either. Documenting the most common ones with examples seems like a good idea, but it's a lot of new content.

Here's how it looks currently with just a few items stubbed out:

Nomenclature

Some things I'd like feedback on:
- Should nomenclature be it's own section, split from the main HTML and CSS ones? Perhaps as a glossary?
- What level of detail is too much? Should we do into every type of selector?
- Is there another format that would serve this better?

<3

### CODE REVIEW

**Comment by castrolem** [comment]
I think you should have it in another section. I like to use the BEM foundation for naming, there's also a great foundation for names in the book SMACSS

**Comment by onyxraven** [comment]
A lot of guides/etc have a nomenclature/usage/glossary section.  I think its important and gets everyone on the same page when describing things, in this guide or otherwise.

**Comment by cironunes** [comment]
IMHO it would be nice to keep it in the same page and it should describe just the generic rules with some examples, (not so much details).

**Comment by mdo** [comment]
> I think you should have it in another section. I like to use the BEM foundation for naming, there's also a great foundation for names in the book SMACSS

@Castrolem That's not what this is about.

**Comment by cordevx2** [comment]
I belongs as part of the CSS section. I'd put it at the end.

**Comment by isrob** [comment]
I think there's value in it as a separate section so long as it's kept brief and doesn't turn into a crash course in CSS. Users requiring that level of tuition aren't your audience.

**Comment by bluetidepro** [comment]
I like the idea of having it as its own glossary section of some sort. Maybe use the `abbr` tag also, for any abbreviations/acronyms (if any). That way you could also add more things to explain later (things that aren't necessarily related to CSS only).

**Comment by ryanmillerdev** [comment]
I'm for using this section as a glossary - and perhaps not including it in the central flow of the guide. Would definitely point out its existence early on so that readers can jump to it if they need a refresher.

**Comment by cvrebert** [comment]
Typo: "Propery"

**Comment by mdo** [comment]
Punting on this for now.

**Pull request closed without merging**
