### PR TITLE
Add another chinese translation

### PR DESCRIPTION
**Pull request by wangsai**
Added language name in native language and english as note.
Is it ok?

### CODE REVIEW

**Comment by wangsai** [comment]
I can't find your traditional chinese translation @JuanitoFatas !

**Comment by JuanitoFatas** [comment]
@wangsai Traditional Chinese one is here: http://juanitofatas.github.io/code-guide

**Comment by wangsai** [comment]
coudle i leave language name in native language and note in english? @mdo

**Comment by mdo** [comment]
Sorry for the delayed response—having both works for me. Please open a new PR to address it if you'd like.

**Pull request closed without merging**
