### PR TITLE
Add Chinese translation.

### PR DESCRIPTION
**Pull request by wangsai**

### CODE REVIEW

**Comment by mdo** [comment]
We already have a Chinese translation—does this one differ much?

**Comment by mdo** [comment]
Closing out until we hear more.

**Comment by wangsai** [comment]
Sorry for my late reply.
The  difference is the comprehension of the original text and corresponding translation.
One more translation, one more choice.

**Comment by mdo** [comment]
Gotcha. Can you open a new PR and add this to the list in the appropriate position? The list is now alphabetized by language name in English.

**Pull request closed without merging**
